import type { Metadata } from "next";
import { Header } from "@/components/Shared/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[640px] m-auto px-5">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
